services:
  - type: web
    name: apm-universal-kit
    runtime: node
    rootDir: Documents/Work/Projects/APM/apm-dashboard
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
